
MODEL = {
    "en":"en_core_web_md",
    "ru":"ru_core_news_md"
}
#/л|мг/дм³|г/л|г/дм³|мг/куб\.м


# Шаг 1: Оставляем регулярки чистыми базами (добавили "л", "дм³", "м³", "м3" в основной список)
UNITS_REGEX_RU = r"(?:мг|МПа|мВ|В|[°][СС]|мм|мкм|м|м3|м2|%|ч|сут|т/сут|л|дм³|м³|м3)"
UNITS_REGEX_EN = r"(?:mg|g|MPa|mV|V|°C|mm|µm|um|m|%|h|hrs|days|t|L|dm3|m3)"

patterns = {
    "ru": [
        # === VALUE_RANGE ===
        # Слитный (например, "200-300мг/л")
        {
            "label": "VALUE_RANGE",
            "pattern": [{"TEXT": {"REGEX": r"^\d+[-–]\d+" + UNITS_REGEX_RU + r"(?:\s*/\s*" + UNITS_REGEX_RU + r")?$"}}]
        },
        # Раздельный БЕЗ дроби (например, "200–300 мг")
        {
            "label": "VALUE_RANGE",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+[-–]\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },
        # Раздельный С ДРОБЬЮ (например, "200–300 мг/л" — все токены обязательны!)
        {
            "label": "VALUE_RANGE",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+[-–]\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },

        # === VALUE_LIMIT ===
        # Слитный (например, "≤1000мг/дм³")
        {
            "label": "VALUE_LIMIT",
            "pattern": [{"TEXT": {"REGEX": r"^[≤≥<>=]+\d+" + UNITS_REGEX_RU + r"(?:\s*/\s*" + UNITS_REGEX_RU + r")?$"}}]
        },
        # Раздельный тип 1 БЕЗ дроби (например, "≤1000 мг")
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },
        # Раздельный тип 1 С ДРОБЬЮ (например, "≤1000 мг/дм³")
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },
        # Раздельный тип 2 БЕЗ дроби (например, "≤ 1000 мг")
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+$"}}, 
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },
        # Раздельный тип 2 С ДРОБЬЮ (например, "≤ 1000 мг/дм³")
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+$"}}, 
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },

        # === VALUE_EXACT ===
        # Раздельный БЕЗ дроби (Пример: "1500 °C", "15 мг")
        {
            "label": "VALUE_EXACT",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },
        # Раздельный С ДРОБЬЮ (Пример: "15 мг/л")
        {
            "label": "VALUE_EXACT",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_RU + r"$"}}
            ]
        },
        # Слитный (например, "1500°C", "20%")
        {
            "label": "VALUE_EXACT",
            "pattern": [{"TEXT": {"REGEX": r"^\d+" + UNITS_REGEX_RU + r"(?:\s*/\s*" + UNITS_REGEX_RU + r")?$"}}]
        }
    ],
    
    "en": [
        # === VALUE_RANGE ===
        {
            "label": "VALUE_RANGE",
            "pattern": [{"TEXT": {"REGEX": r"^\d+[-–]\d+" + UNITS_REGEX_EN + r"(?:\s*/\s*" + UNITS_REGEX_EN + r")?$"}}]
        },
        {
            "label": "VALUE_RANGE",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+[-–]\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        {
            "label": "VALUE_RANGE",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+[-–]\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        # === VALUE_LIMIT ===
        {
            "label": "VALUE_LIMIT",
            "pattern": [{"TEXT": {"REGEX": r"^[≤≥<>=]+\d+" + UNITS_REGEX_EN + r"(?:\s*/\s*" + UNITS_REGEX_EN + r")?$"}}]
        },
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+$"}}, 
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        {
            "label": "VALUE_LIMIT",
            "pattern": [
                {"TEXT": {"REGEX": r"^[≤≥<>=]+$"}}, 
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        # === VALUE_EXACT ===
        {
            "label": "VALUE_EXACT",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        {
            "label": "VALUE_EXACT",
            "pattern": [
                {"TEXT": {"REGEX": r"^\d+$"}}, 
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}},
                {"TEXT": {"REGEX": r"^/$"}},
                {"TEXT": {"REGEX": r"^" + UNITS_REGEX_EN + r"$"}}
            ]
        },
        {
            "label": "VALUE_EXACT",
            "pattern": [{"TEXT": {"REGEX": r"^\d+" + UNITS_REGEX_EN + r"(?:\s*/\s*" + UNITS_REGEX_EN + r")?$"}}]
        }
    ]
}







dictionary = {
  "Material": {
    "ru": {
      "медь": { "synonyms": ["cu", "cu-содержащие", "черновая медь", "медный концентрат", "катодная медь", "медный кек"] },
      "никель": { "synonyms": ["ni", "ni-содержащие", "черновой никель", "никелевый концентрат", "катодный никель", "никелевый файнштейн"] },
      "кобальт": { "synonyms": ["co", "co-содержащие", "черновой кобальт", "кобальтовый концентрат", "катодный кобальт"] },
      "платина": { "synonyms": ["pt", "платиноиды", "металлы платиновой группы", "мпг", "платиновый концентрат"] },
      "палладий": { "synonyms": ["pd", "pd-содержащие", "палладиевый концентрат"] },
      "родий": { "synonyms": ["rh", "родиевый концентрат"] },
      "иридий": { "synonyms": ["ir"] },
      "осмий": { "synonyms": ["os"] },
      "рутений": { "synonyms": ["ru"] },
      "золото": { "synonyms": ["au", "au-содержащие", "золотосодержащий", "золотой концентрат", "доре-слиток"] },
      "серебро": { "synonyms": ["ag", "ag-содержащие", "серебряный концентрат"] },
      "селен": { "synonyms": ["se", "селенсодержащий", "селеновый шлам"] },
      "теллур": { "synonyms": ["te", "теллурсодержащий", "теллуровый шлам"] },
      "файнштейн": { "synonyms": ["медно-никелевый файнштейн", "штейн", "конвертерный штейн", "искусственный штейн", "файнштейн плавки"] },
      "штейн": { "synonyms": ["медный штейн", "никелевый штейн", "медно-никелевый штейн", "конвертерный штейн"] },
      "шлак": { "synonyms": ["отвальный шлак", "текучий шлак", "силикатный шлак", "богатый шлак", "шлаковый расплав", "металлургический шлак"] },
      "кек": { "synonyms": ["фильтр-кек", "цементационный кек", "осадок", "вторичный кек", "никелевый кек", "медный кек"] },
      "пульпа": { "synonyms": ["пульпа выщелачивания", "шламовая пульпа", "флотационная пульпа", "суспензия"] },
      "раствор": { "synonyms": ["сульфатный раствор", "хлоридный раствор", "оборотный раствор", "продукционный раствор", "бедный раствор", "жидкая фаза"] },
      "электролит": { "synonyms": ["медный электролит", "никелевый электролит", "сульфатный электролит", "хлоридный электролит", "рафинировочный электролит"] },
      "анод": { "synonyms": ["анод", "никелевый анод", "медный анод", "анодная пластина", "растворимый анод"] },
      "катод": { "synonyms": ["катод", "никелевый катод", "медный катод", "стартовый катод", "катодное основание"] },
      "реагент": { "synonyms": ["флотационный реагент", "химический реагент", "реагент-депрессор", "реагент-активатор", "пенообразователь", "собиратель", "модификатор"] },
      "сера": { "synonyms": ["s", "элементарная сера", "серосодержащий"] },
      "кварц": { "synonyms": ["sio₂", "кварцевый песок", "флюс"] },
      "известняк": { "synonyms": ["cao", "флюс", "известь"] },
      "пирит": { "synonyms": ["fes₂", "серный колчедан"] },
      "магний": { "synonyms": ["mg", "mgcl₂", "хлористый магний"] },
      "хлор": { "synonyms": ["cl₂", "газообразный хлор", "хлор-газ", "хлорная вода"] },
      "хлороводород": { "synonyms": ["hcl", "соляная кислота"] },
      "серная кислота": { "synonyms": ["h₂so₄", "купоросное масло", "электролит"] },
      "аммиак": { "synonyms": ["nh₃", "аммиачная вода", "водный аммиак"] },
      "сульфат аммония": { "synonyms": ["(nh₄)₂so₄", "сульфат аммония"] },
      "хлорид никеля": { "synonyms": ["nicl₂", "хлористый никель"] },
      "хлорид меди": { "synonyms": ["cucl", "cucl₂", "хлористая медь"] },
      "сульфат меди": { "synonyms": ["cuso₄", "медный купорос"] },
      "сульфат никеля": { "synonyms": ["niso₄", "никелевый купорос"] },
      "шлам": { "synonyms": ["анодный шлам", "медный шлам", "никелевый шлам", "селеновый шлам", "теллуровый шлам", "драгметалльный шлам", "пенный продукт", "хвосты флотации", "отходы обогащения"] },
      "хвосты": { "synonyms": ["хвосты обогащения", "отвальные хвосты", "флотационные хвосты", "твердые отходы"] },
      "концентрат": { "synonyms": ["медный концентрат", "никелевый концентрат", "кобальтовый концентрат", "кпп", "кмсп", "коллективный концентрат", "пирротиновый концентрат", "малоникелистый концентрат", "драгметалльный концентрат"] },
      "руда": { "synonyms": ["сульфидная руда", "окисленная руда", "медно-никелевая руда", "медная руда", "никелевая руда", "полиметаллическая руда", "вкрапленная руда", "густовкрапленная руда", "массивная руда", "брекчированная руда"] },
      "продукт": { "synonyms": ["товарный продукт", "промежуточный продукт", "возвратный продукт"] },
      "рафинат": { "synonyms": ["обедненный электролит", "отработанный электролит"] },
      "сульфид": { "synonyms": ["cu₂s", "nis", "сульфидный концентрат"] },
      "оксид": { "synonyms": ["оксид никеля", "оксид меди", "nio", "cuo"] },
      "металл": { "synonyms": ["тяжелые металлы", "цветные металлы", "благородные металлы", "редкие металлы", "металлическая фаза"] },
      "титан": { "synonyms": ["ti", "титановый анод", "титановая футеровка"] },
      "свинец": { "synonyms": ["pb", "свинцовый анод"] },
      "графит": { "synonyms": ["графитовая футеровка", "углерод"] },
            "мышьяк": { "synonyms": ["as", "мышьяксодержащие", "мышьяковистый", "арсен"] },
      "висмут": { "synonyms": ["bi", "висмутовый", "свинцово-висмутовый сплав"] },
      "сурьма": { "synonyms": ["sb", "сурьмянистый", "стибий"] },
      "кадмий": { "synonyms": ["cd", "кадмиевый", "кадмийсодержащий"] },
      "цинк": { "synonyms": ["zn", "цинковый", "цинксодержащий", "цинковый концентрат"] },
      "железо": { "synonyms": ["fe", "железистый", "fe-содержащие", "ферро-никель", "окись железа"] },
      "кремний": { "synonyms": ["si", "кремнезем", "силикаты", "диоксид кремния"] },
      "алюминий": { "synonyms": ["al", "алюминатный", "глинозем", "al₂o₃"] },
      "кальций": { "synonyms": ["ca", "известковый", "гипс", "карбонат кальция"] },
      "натрий": { "synonyms": ["na", "сода", "едкий натр", "соляной раствор"] },
      "марганец": { "synonyms": ["mn", "марганцевый", "пиролюзит"] },
      "хром": { "synonyms": ["cr", "хромистый", "хромат"] },
      "молибден": { "synonyms": ["mo", "молибдатный", "молибденовый концентрат"] },
      "рений": { "synonyms": ["re", "рениевый", "рениевсодержащий"] },
      "германий": { "synonyms": ["ge", "германиевый"] },
      "индий": { "synonyms": ["in", "индиевый"] },
      "галлий": { "synonyms": ["ga", "галлиевый"] },
      "тантал": { "synonyms": ["ta", "танталовый"] },
      "ниобий": { "synonyms": ["nb", "ниобиевый"] },
      "цирконий": { "synonyms": ["zr", "циркониевый"] },
      "гафний": { "synonyms": ["hf", "гафниевый"] },
      "ванадий": { "synonyms": ["v", "ванадатный", "пентоксид ванадия"] },
      "вольфрам": { "synonyms": ["w", "вольфрамовый", "вольфрамит"] },
      "олово": { "synonyms": ["sn", "оловянный", "касситерит"] },
      "свинец": { "synonyms": ["pb", "свинцовый", "галенит", "свинцовый анод"] },
      "титан": { "synonyms": ["ti", "титановый", "диоксид титана"] },
      "бериллий": { "synonyms": ["be", "бериллиевый"] },
      "литий": { "synonyms": ["li", "литиевый", "литиевые соли"] },
      "редкоземельные металлы": { "synonyms": ["рзм", "лантаноиды", "церий", "неодим", "празеодим", "самарий", "европий", "гадолиний", "тербий", "диспрозий", "гольмий", "эрбий", "тулий", "иттербий", "лютеций", "скандий", "иттрий", "редкоземельное сырье"] },
      "шлак обедненный": { "synonyms": ["отвальный шлак", "конвертерный шлак", "шлак фьюминг-процесса", "силикатный шлак"] },
      "шлак богатый": { "synonyms": ["промежуточный шлак", "передельный шлак", "шлак с высоким содержанием металла"] },
      "файнштейн бедный": { "synonyms": ["штейн после конвертирования", "штейн обедненный"] },
      "промежуточный продукт": { "synonyms": ["полупродукт", "некондиционный продукт", "оборотный продукт", "промпродукт"] },
      "благородные металлы": { "synonyms": ["драгоценные металлы", "золото-серебряный сплав", "металлы платиновой группы", "аффинированные металлы"] },
      "оксиды": { "synonyms": ["оксидная пленка", "оксидный концентрат", "прокаленная окалина"] },
      "сульфиды": { "synonyms": ["сульфидный концентрат", "сульфидная руда", "колчедан"] },
      "хлориды": { "synonyms": ["хлоридный раствор", "хлоридная соль", "хлорная соль"] },
      "нитраты": { "synonyms": ["селитра", "аммиачная селитра", "натриевая селитра"] },
      "карбонаты": { "synonyms": ["сода", "зола", "карбонатная пульпа"] },
      "гидроксиды": { "synonyms": ["щелочь", "гидроксид натрия", "гидроксид калия"] },
      "пек": { "synonyms": ["каменноугольный пек", "связующее", "электродный пек"] },
      "коксик": { "synonyms": ["кокс", "коксовая мелочь", "коксовый остаток"] },
      "флюс": { "synonyms": ["флюсующий материал", "кварцит", "борная кислота"] }
    },
    "en": {
      "copper": { "synonyms": ["cu", "cu-bearing", "blister copper", "copper concentrate", "copper cathode", "cement copper"] },
      "nickel": { "synonyms": ["ni", "ni-bearing", "blister nickel", "nickel concentrate", "nickel cathode", "nickel matte"] },
      "cobalt": { "synonyms": ["co", "co-bearing", "blister cobalt", "cobalt concentrate", "cobalt cathode"] },
      "platinum": { "synonyms": ["pt", "platinum group metals", "pgm", "platinum concentrate"] },
      "palladium": { "synonyms": ["pd", "pd-bearing", "palladium concentrate"] },
      "rhodium": { "synonyms": ["rh"] },
      "iridium": { "synonyms": ["ir"] },
      "osmium": { "synonyms": ["os"] },
      "ruthenium": { "synonyms": ["ru"] },
      "gold": { "synonyms": ["au", "gold-bearing", "doré", "gold concentrate"] },
      "silver": { "synonyms": ["ag", "silver concentrate"] },
      "selenium": { "synonyms": ["se", "selenium-containing", "selenium sludge", "selenium bearing"] },
      "tellurium": { "synonyms": ["te", "tellurium sludge"] },
      "matte": { "synonyms": ["copper-nickel matte", "converter matte", "artificial matte", "furnace matte"] },
      "slag": { "synonyms": ["waste slag", "molten slag", "silicate slag", "iron silicate slag", "tailings slag", "metallurgical slag"] },
      "cake": { "synonyms": ["filter cake", "cementation cake", "precipitate", "secondary cake", "nickel cake", "copper cake"] },
      "pulp": { "synonyms": ["leach pulp", "slurry", "flotation pulp", "suspension"] },
      "solution": { "synonyms": ["sulfate solution", "chloride solution", "circulating solution", "pregnant solution", "barren solution", "liquid phase"] },
      "electrolyte": { "synonyms": ["copper electrolyte", "nickel electrolyte", "sulfate electrolyte", "chloride electrolyte", "refining electrolyte"] },
      "anode": { "synonyms": ["nickel anode", "copper anode", "soluble anode"] },
      "cathode": { "synonyms": ["nickel cathode", "copper cathode", "starter sheet", "cathode blank"] },
      "reagent": { "synonyms": ["froth flotation reagent", "depressant", "collector", "activator", "frother", "modifier"] },
      "sulfur": { "synonyms": ["s", "elemental sulfur", "sulfur-containing"] },
      "quartz": { "synonyms": ["sio₂", "silica", "flux"] },
      "limestone": { "synyms": ["cao", "flux", "quicklime"] },
      "pyrite": { "synonyms": ["fes₂", "iron pyrite"] },
      "magnesium": { "synonyms": ["mg", "mgcl₂", "magnesium chloride"] },
      "chlorine": { "synonyms": ["cl₂", "chlorine gas"] },
      "hydrogen chloride": { "synonyms": ["hcl", "hydrochloric acid"] },
      "sulfuric acid": { "synonyms": ["h₂so₄", "oil of vitriol"] },
      "ammonia": { "synonyms": ["nh₃", "aqueous ammonia"] },
      "ammonium sulfate": { "synonyms": ["(nh₄)₂so₄"] },
      "nickel chloride": { "synonyms": ["nicl₂"] },
      "copper chloride": { "synonyms": ["cucl", "cucl₂"] },
      "copper sulfate": { "synonyms": ["cuso₄"] },
      "nickel sulfate": { "synonyms": ["niso₄"] },
      "sludge": { "synonyms": ["anode slime", "copper sludge", "nickel sludge", "selenium sludge", "tellurium sludge", "precious metal sludge", "flotation froth", "tailings", "concentration tailings"] },
      "tailings": { "synonyms": ["concentration tailings", "waste rock", "flotation tailings", "solid waste"] },
      "concentrate": { "synonyms": ["copper concentrate", "nickel concentrate", "cobalt concentrate", "kpp", "kmsp", "bulk concentrate", "pyrrhotite concentrate", "low-nickel concentrate", "precious metal concentrate"] },
      "ore": { "synonyms": ["sulfide ore", "oxide ore", "copper-nickel ore", "copper ore", "nickel ore", "polymetallic ore", "disseminated ore", "massive ore", "brecciated ore"] },
      "product": { "synonyms": ["commercial product", "intermediate product", "recycled product"] },
      "raffinate": { "synonyms": ["depleted electrolyte", "spent electrolyte"] },
      "sulfide": { "synonyms": ["cu₂s", "nis", "sulfide concentrate"] },
      "oxide": { "synonyms": ["nickel oxide", "copper oxide", "nio", "cuo"] },
      "metal": { "synonyms": ["heavy metals", "non-ferrous metals", "precious metals", "rare metals", "metallic phase"] },
      "titanium": { "synonyms": ["ti", "titanium anode", "titanium lining"] },
      "lead": { "synonyms": ["pb", "lead anode"] },
      "graphite": { "synonyms": ["graphite lining", "carbon"] },
      "arsenic": { "synonyms": ["as", "arsenical", "white arsenic"] },
      "bismuth": { "synonyms": ["bi", "bismuth-alloy", "lead-bismuth alloy"] },
      "antimony": { "synonyms": ["sb", "stibium", "antimonial", "regulus"] },
      "cadmium": { "synonyms": ["cd", "cadmium-bearing"] },
      "zinc": { "synonyms": ["zn", "zinc concentrate", "zinc blende", "sphalerite"] },
      "iron": { "synonyms": ["fe", "ferrous", "iron-bearing", "ferro-nickel", "iron oxide"] },
      "silicon": { "synonyms": ["si", "silica", "silicates", "quartz", "silicon dioxide"] },
      "aluminum": { "synonyms": ["al", "alumina", "aluminate", "al₂o₃"] },
      "calcium": { "synonyms": ["ca", "lime", "limestone", "gypsum"] },
      "sodium": { "synonyms": ["na", "soda", "caustic soda", "sodium chloride"] },
      "manganese": { "synonyms": ["mn", "manganiferous", "pyrolusite"] },
      "chromium": { "synonyms": ["cr", "chromate", "chromite"] },
      "molybdenum": { "synonyms": ["mo", "molybdenite", "molybdenum concentrate"] },
      "rhenium": { "synonyms": ["re", "rhenium-bearing"] },
      "germanium": { "synonyms": ["ge", "germanium-bearing"] },
      "indium": { "synonyms": ["in", "indium-bearing"] },
      "gallium": { "synonyms": ["ga", "gallium-bearing"] },
      "tantalum": { "synonyms": ["ta", "tantalum-bearing"] },
      "niobium": { "synonyms": ["nb", "niobium-bearing", "columbium"] },
      "zirconium": { "synonyms": ["zr", "zirconium-bearing"] },
      "hafnium": { "synonyms": ["hf", "hafnium-bearing"] },
      "vanadium": { "synonyms": ["v", "vanadate", "vanadium pentoxide"] },
      "tungsten": { "synonyms": ["w", "wolfram", "scheelite", "wolframite"] },
      "tin": { "synonyms": ["sn", "cassiterite", "stannic"] },
      "lead": { "synonyms": ["pb", "galena", "lead slag", "lead-bearing"] },
      "titanium": { "synonyms": ["ti", "titanium dioxide", "titanium sponge"] },
      "beryllium": { "synonyms": ["be", "beryllium-bearing"] },
      "lithium": { "synonyms": ["li", "lithium salts", "spodumene", "lithium-bearing"] },
      "rare earth elements": { "synonyms": ["ree", "lanthanides", "cerium", "neodymium", "praseodymium", "samarium", "europium", "gadolinium", "terbium", "dysprosium", "holmium", "erbium", "thulium", "ytterbium", "lutetium", "scandium", "yttrium", "rare earth concentrate"] },
      "lean slag": { "synonyms": ["waste slag", "discard slag", "silicate slag", "tailings slag"] },
      "rich slag": { "synonyms": ["intermediate slag", "high-grade slag", "converter slag"] },
      "lean matte": { "synonyms": ["primary matte", "low-grade matte"] },
      "intermediate product": { "synonyms": ["semi-product", "off-grade product", "recycled product", "middling"] },
      "precious metals": { "synonyms": ["noble metals", "gold-silver alloy", "pgm", "refined metals"] },
      "oxides": { "synonyms": ["oxide film", "oxide concentrate", "calcine", "oxide scale"] },
      "sulfides": { "synonyms": ["sulfide concentrate", "sulfide ore", "pyrite", "pyrrhotite"] },
      "chlorides": { "synonyms": ["chloride solution", "chloride salt", "chlorine salt"] },
      "nitrates": { "synonyms": ["saltpeter", "ammonium nitrate", "sodium nitrate"] },
      "carbonates": { "synonyms": ["soda", "ash", "carbonate pulp"] },
      "hydroxides": { "synonyms": ["alkali", "sodium hydroxide", "potassium hydroxide", "caustic"] },
      "pitch": { "synonyms": ["coal tar pitch", "binder", "electrode binder"] },
      "coke": { "synonyms": ["coke breeze", "coke fines", "coke residue", "metallurgical coke"] },
      "flux": { "synonyms": ["fluxing agent", "quartzite", "borax", "flux material"] }
    
    }
  },
  "Process": {
    "ru": {
      "выщелачивание": { "synonyms": ["автоклавное выщелачивание", "атмосферное выщелачивание", "окислительное выщелачивание", "кислотное выщелачивание", "хлорное выщелачивание", "выщелачивание под давлением", "реакция растворения", "гидрометаллургическое извлечение"] },
      "хлорирование": { "synonyms": ["хлорное растворение", "обработка хлором", "газофаза", "обработка cl₂"] },
      "флотация": { "synonyms": ["флотационное обогащение", "пенная флотация", "коллективная флотация", "селективная флотация", "флотация сульфидов", "флотация руд"] },
      "плавка": { "synonyms": ["плавка концентратов", "плавка в печи Ванюкова", "штейнплавка", "открытая плавка", "восстановительная плавка", "пирометаллургия"] },
      "обжиг": { "synonyms": ["окислительный обжиг", "высокотемпературный обжиг", "обжиг в печи кипящего слоя", "термическая обработка"] },
      "электролиз": { "synonyms": ["электрорафинирование", "электроэкстракция", "электролитическое рафинирование", "электролитическое осаждение", "электролитическое извлечение"] },
      "цементация": { "synonyms": ["цементационное осаждение", "контактное осаждение", "осаждение металлов", "извлечение цементацией"] },
      "рафинирование": { "synonyms": ["огневое рафинирование", "электролитическое рафинирование", "очистка металлов", "аффинаж", "облагораживание"] },
      "конвертирование": { "synonyms": ["конвертерная плавка", "продувка штейна", "конвертерный процесс", "процесс в конвертере"] },
      "сушка": { "synonyms": ["сушка концентрата", "сушка кека", "термическая сушка", "обезвоживание"] },
      "фильтрация": { "synonyms": ["фильтрация пульпы", "вакуум-фильтрация", "пресс-фильтрация", "разделение твердой и жидкой фазы"] },
      "сгущение": { "synonyms": ["сгущение пульпы", "осаждение", "ступение", "пастовое сгущение"] },
      "смешивание": { "synonyms": ["смешивание реагентов", "приготовление пульпы", "перемешивание", "шихтовка"] },
      "дозирование": { "synonyms": ["дозировка реагентов", "точное дозирование", "подача компонентов"] },
      "измельчение": { "synonyms": ["дробление", "помол", "мокрое измельчение", "сухое измельчение", "дезинтеграция"] },
      "классификация": { "synonyms": ["грохочение", "сепарация по крупности", "гидроциклонирование"] },
      "сортировка": { "synonyms": ["рудно-породная сортировка", "сепарация", "автоматическая сортировка"] },
      "десорбция": { "synonyms": ["десорбция металлов", "регенерация", "извлечение из раствора"] },
      "нейтрализация": { "synonyms": ["нейтрализация кислоты", "нейтрализация стоков", "осаждение примесей"] },
      "осаждение": { "synonyms": ["гидрометаллургическое осаждение", "соосаждение", "кристаллизация", "выпадение в осадок"] },
      "дистилляция": { "synonyms": ["ректификация", "перегонка", "выделение паров"] },
      "испарение": { "synonyms": ["концентрирование", "выпаривание", "упаривание"] },
      "газоочистка": { "synonyms": ["очистка отходящих газов", "пылегазоочистка", "десульфуризация", "нейтрализация газов"] },
      "абсорбция": { "synonyms": ["абсорбция газов", "хемосорбция", "поглощение"] },
      "декантация": { "synonyms": ["декантация жидкости", "отстаивание", "осветление"] },
      "грануляция": { "synonyms": ["гранулирование", "окускование", "агломерация", "пиллетирование"] },
      "нагрев": { "synonyms": ["предварительный нагрев", "плавка", "подогрев", "термическая обработка"] },
      "охлаждение": { "synonyms": ["закалка", "кристаллизация расплава", "термообработка"] },
      "подготовка сырья": { "synonyms": ["рудоподготовка", "подготовка концентрата", "шихтоприготовление"] },
      "контроль качества": { "synonyms": ["анализ", "лабораторный контроль", "технологический контроль", "испытания"] },
      "автоклавное окисление": { "synonyms": ["автоклавный процесс", "окислительное выщелачивание", "давлентное окисление"] },
      "биовыщелачивание": { "synonyms": ["бактериальное выщелачивание", "биогидрометаллургия", "окисление бактериями"] },
      "электроэкстракция": { "synonyms": ["извлечение током", "электровиннинг"] },
      "аффинаж": { "synonyms": ["аффинаж драгметаллов", "очистка", "рафинирование", "облагораживание"] },
      "дефлокуляция": { "synonyms": ["разрушение флокул", "обработка пульпы", "дезагрегация"] },
      "флокуляция": { "synonyms": ["агрегация", "образование флокул", "коагуляция"] },
      "регенерация": { "synonyms": ["восстановление", "рециклинг", "повторное использование", "рекуперация"] },
      "газообмен": { "synonyms": ["аэрация", "оксигенация", "продувка газом", "насыщение кислородом"] },
      "отстаивание": { "synonyms": ["седиментация", "осаждение твердой фазы"] },
      "дробление": { "synonyms": ["крупное дробление", "среднее дробление", "мелкое дробление"] },
      "сгущение хвостов": { "synonyms": ["пастовое сгущение", "обезвоживание хвостов", "подготовка хвостов"] },
      "пирометаллургический процесс": { "synonyms": ["высокотемпературная обработка", "плавильный передел"] },
      "гидрометаллургический процесс": { "synonyms": ["мокрая металлургия", "водная экстракция"] },
            "автоклавное выщелачивание": { "synonyms": ["автоклавный процесс", "окислительное выщелачивание", "давлентное выщелачивание", "autoclave leaching"] },
      "агломерация": { "synonyms": ["спекание", "окускование", "грануляция", "пиллетирование", "агломерационный процесс"] },
      "бактериальное выщелачивание": { "synonyms": ["биовыщелачивание", "биосорбция", "микробиологическое выщелачивание", "bioleaching"] },
      "вакуумирование": { "synonyms": ["вакуумное испарение", "вакуумная дистилляция", "вакуумная дегазация"] },
      "восстановление": { "synonyms": ["редукция", "восстановительная плавка", "восстановительный обжиг", "водородное восстановление"] },
      "выпаривание": { "synonyms": ["упаривание", "концентрирование", "выпарка", "эвапорация"] },
      "газификация": { "synonyms": ["газогенерация", "пиролиз", "термическое разложение"] },
      "гидроциклонирование": { "synonyms": ["классификация в гидроциклоне", "разделение в гидроциклоне", "обогащение в гидроциклоне"] },
      "гравитационное обогащение": { "synonyms": ["гравитация", "отсадка", "концентрация на столах", "гравитационная сепарация"] },
      "дегазация": { "synonyms": ["десорбция газов", "удаление газов", "деаэрация"] },
      "дезинтеграция": { "synonyms": ["диспергирование", "измельчение", "дезагрегация", "разрушение частиц"] },
      "депрессия": { "synonyms": ["депрессорная обработка", "подавление флотации", "реагентная депрессия"] },
      "десорбция": { "synonyms": ["элюирование", "вымывание", "извлечение из ионита", "регенерация сорбента"] },
      "дистилляция": { "synonyms": ["перегонка", "ректификация", "фракционная перегонка"] },
      "жидкая экстракция": { "synonyms": ["экстракция", "сольвентная экстракция", "жидкостная экстракция", "извлечение экстракцией"] },
      "закалка": { "synonyms": ["кристаллизация расплава", "охлаждение", "шлаковая закалка"] },
      "замена реагентов": { "synonyms": ["реагентная подпитка", "корректировка реагентного режима"] },
      "ионный обмен": { "synonyms": ["сорбция", "ионообменная смола", "хемосорбция"] },
      "классификация": { "synonyms": ["грохочение", "сепарация по крупности", "фракционирование"] },
      "кристаллизация": { "synonyms": ["выкристаллизовывание", "кристаллизационный процесс", "осаждение кристаллов"] },
      "магнитная сепарация": { "synonyms": ["магнитное обогащение", "магнитная дешламация", "выделение магнитной фракции"] },
      "нейтрализация": { "synonyms": ["щелочная нейтрализация", "кислотная нейтрализация", "осаждение примесей"] },
      "обезвоживание": { "synonyms": ["сушка", "фильтрация", "центрифугирование", "обезвоживание хвостов"] },
      "обжиг": { "synonyms": ["окислительный обжиг", "сульфатизирующий обжиг", "хлорирующий обжиг", "магнетизирующий обжиг"] },
      "обогащение": { "synonyms": ["обогащение руды", "переработка сырья", "углубленная переработка"] },
      "окисление": { "synonyms": ["оксидирование", "продувка кислородом", "окислительное выщелачивание"] },
      "отстаивание": { "synonyms": ["седиментация", "осветление", "разделение фаз"] },
      "очистка": { "synonyms": ["рафинирование", "аффинаж", "глубокая очистка", "очистка от примесей"] },
      "перемешивание": { "synonyms": ["агитация", "гомогенизация", "интенсивное перемешивание"] },
      "пиролиз": { "synonyms": ["термическое разложение", "коксование", "полукоксование"] },
      "плавка": { "synonyms": ["штейнплавка", "конвертерная плавка", "восстановительная плавка", "плавка в печи"] },
      "продувка": { "synonyms": ["аэрация", "барботаж", "насыщение газом", "продувка воздухом"] },
      "растворение": { "synonyms": ["растворение металлов", "переход в раствор", "химическое растворение"] },
      "сгущение": { "synonyms": ["ступение", "утолщение пульпы", "пастовое сгущение", "концентрирование"] },
      "смешивание": { "synonyms": ["шихтовка", "приготовление шихты", "блендинг", "гомогенизация"] },
      "сорбция": { "synonyms": ["адсорбция", "хемосорбция", "ионообменная сорбция", "осаждение на сорбенте"] },
      "спекание": { "synonyms": ["агломерация", "термическое спекание", "образование спеков"] },
      "сушка": { "synonyms": ["термическая сушка", "высушивание", "дегидратация"] },
      "фильтрация": { "synonyms": ["вакуум-фильтрация", "прессование", "отжим", "разделение на фильтре"] },
      "флотация": { "synonyms": ["пенная флотация", "коллективная флотация", "селективная флотация", "флотация с депрессорами"] },
      "хлорирование": { "synonyms": ["хлорная обработка", "насыщение хлором", "хлоридное выщелачивание"] },
      "цементация": { "synonyms": ["осаждение металлов", "контактное осаждение", "жидкая цементация", "восстановление металлов"] },
      "электролиз": { "synonyms": ["электрорафинирование", "электроэкстракция", "электролитическое осаждение"] }
    },
    "en": {
      "leaching": { "synonyms": ["pressure leaching", "atmospheric leaching", "acid leaching", "chlorine leaching", "oxidative leaching", "dissolution", "hydrometallurgical recovery"] },
      "chlorination": { "synonyms": ["chloride leaching", "chlorine treatment", "gas phase chlorination"] },
      "flotation": { "synonyms": ["froth flotation", "bulk flotation", "selective flotation", "sulfide flotation", "ore flotation"] },
      "smelting": { "synonyms": ["matte smelting", "pyrometallurgy", "concentrate smelting", "vanyukov smelting"] },
      "roasting": { "synonyms": ["oxidative roasting", "high temperature roasting", "fluidized bed roasting", "thermal treatment"] },
      "electrolysis": { "synonyms": ["electrorefining", "electrowinning", "electrolytic refining"] },
      "cementation": { "synonyms": ["cement precipitation", "contact precipitation", "metal displacement"] },
      "refining": { "synonyms": ["fire refining", "electrolytic refining", "metal purification", "refining process", "precious metal refining"] },
      "converting": { "synonyms": ["converter blowing", "matte conversion", "bessemerizing"] },
      "drying": { "synonyms": ["concentrate drying", "cake drying", "thermal drying", "dewatering"] },
      "filtration": { "synonyms": ["pulp filtration", "vacuum filtration", "pressure filtration", "solid-liquid separation"] },
      "thickening": { "synonyms": ["pulp thickening", "settling", "paste thickening"] },
      "mixing": { "synonyms": ["reagent mixing", "pulp preparation", "agitation", "blending"] },
      "dosing": { "synonyms": ["reagent dosing", "precise dosing", "component feeding"] },
      "grinding": { "synonyms": ["crushing", "milling", "wet grinding", "dry grinding", "communition"] },
      "classification": { "synonyms": ["screening", "size separation", "hydrocycloning"] },
      "sorting": { "synonyms": ["ore sorting", "automated sorting", "separation"] },
      "desorption": { "synonyms": ["metal desorption", "regeneration"] },
      "neutralization": { "synonyms": ["acid neutralization", "effluent neutralization", "precipitation of impurities"] },
      "precipitation": { "synonyms": ["hydrometallurgical precipitation", "co-precipitation", "crystallization"] },
      "distillation": { "synonyms": ["rectification", "fractional distillation"] },
      "evaporation": { "synonyms": ["concentration", "liquor concentration"] },
      "gas cleaning": { "synonyms": ["off-gas treatment", "dust collection", "desulfurization", "scrubbing"] },
      "absorption": { "synonyms": ["gas absorption", "chemisorption"] },
      "decantation": { "synonyms": ["liquid decantation", "settling", "clarification"] },
      "granulation": { "synonyms": ["agglomeration", "pelletizing", "nodulizing"] },
      "heating": { "synonyms": ["preheating", "thermal treatment", "melting"] },
      "cooling": { "synonyms": ["quenching", "crystallization", "solidification"] },
      "ore preparation": { "synonyms": ["feed preparation", "concentrate preparation", "batch preparation"] },
      "quality control": { "synonyms": ["analysis", "laboratory control", "process control", "testing"] },
      "autoclave oxidation": { "synonyms": ["pressure oxidation", "autoclave process", "oxidative leaching"] },
      "bioleaching": { "synonyms": ["bacterial leaching", "biomining", "microbial oxidation"] },
      "electrowinning": { "synonyms": ["electrolytic winning", "extraction by current"] },
      "refining": { "synonyms": ["precious metal refining", "purification", "smelting and refining"] },
      "deflocculation": { "synonyms": ["floc breakage", "disaggregation", "pulp treatment"] },
      "flocculation": { "synonyms": ["coagulation", "floc formation", "agglomeration"] },
      "regeneration": { "synonyms": ["recovery", "recycling", "reuse", "recuperation"] },
      "gas exchange": { "synonyms": ["aeration", "oxygenation", "gas sparging"] },
      "sedimentation": { "synonyms": ["settling", "solid-liquid separation", "clarification"] },
      "crushing": { "synonyms": ["primary crushing", "secondary crushing", "tertiary crushing"] },
      "tailings thickening": { "synonyms": ["paste thickening", "tailings dewatering", "tailings preparation"] },
      "pyrometallurgical process": { "synonyms": ["high temperature processing", "smelting stage"] },
      "hydrometallurgical process": { "synonyms": ["aqueous metallurgy", "wet process"] },
            "acid leaching": { "synonyms": ["sulfuric acid leaching", "sulfation", "acid dissolution"] },
      "agglomeration": { "synonyms": ["sintering", "pelletizing", "nodulizing", "briquetting"] },
      "bioleaching": { "synonyms": ["bacterial leaching", "microbial leaching", "bioprocessing"] },
      "calcination": { "synonyms": ["thermal decomposition", "roasting", "heating to decomposition"] },
      "cementation": { "synonyms": ["precipitation", "contact reduction", "metal displacement"] },
      "chlorination": { "synonyms": ["chloride treatment", "chlorine leaching", "gas chlorination"] },
      "classification": { "synonyms": ["screening", "sieving", "size classification", "hydroclassification"] },
      "crystallization": { "synonyms": ["precipitation", "evaporative crystallization", "cooling crystallization"] },
      "dewatering": { "synonyms": ["drying", "filtration", "centrifugation", "thickening"] },
      "digestion": { "synonyms": ["dissolution", "leaching", "solubilization"] },
      "distillation": { "synonyms": ["rectification", "fractional distillation", "evaporation"] },
      "drying": { "synonyms": ["thermal drying", "flash drying", "spray drying"] },
      "electrolysis": { "synonyms": ["electrorefining", "electrowinning", "electrolytic reduction"] },
      "electrowinning": { "synonyms": ["electrolytic winning", "electroextraction", "metal deposition"] },
      "evaporation": { "synonyms": ["concentration", "vaporization", "liquor boiling"] },
      "filtration": { "synonyms": ["pressure filtration", "vacuum filtration", "solid-liquid separation"] },
      "flocculation": { "synonyms": ["coagulation", "aggregation", "sedimentation aid"] },
      "flotation": { "synonyms": ["froth flotation", "bulk flotation", "selective flotation"] },
      "gas scrubbing": { "synonyms": ["wet scrubbing", "dry scrubbing", "gas purification", "acid gas removal"] },
      "gravity separation": { "synonyms": ["gravity concentration", "jigging", "tabling", "spiral concentration"] },
      "grinding": { "synonyms": ["comminution", "milling", "crushing", "pulverizing"] },
      "ion exchange": { "synonyms": ["ion exchange resin", "sorption", "chelation"] },
      "leaching": { "synonyms": ["dissolution", "lixiviation", "extraction", "hydrometallurgical extraction"] },
      "magnetic separation": { "synonyms": ["magnetic concentration", "magnetic beneficiation", "ferrous extraction"] },
      "mixing": { "synonyms": ["blending", "agitation", "homogenization", "suspension"] },
      "neutralization": { "synonyms": ["acid neutralization", "alkaline neutralization", "pH adjustment"] },
      "oxidation": { "synonyms": ["oxygenation", "oxidative leaching", "pressure oxidation", "air sparging"] },
      "precipitation": { "synonyms": ["chemical precipitation", "cementation", "crystallization"] },
      "purification": { "synonyms": ["refining", "cleaning", "scavenging", "impurity removal"] },
      "reduction": { "synonyms": ["reduction smelting", "hydrogen reduction", "de-oxidation"] },
      "roasting": { "synonyms": ["oxidative roasting", "sulfation", "chlorination roasting", "magnetizing roasting"] },
      "sedimentation": { "synonyms": ["settling", "clarification", "decantation"] },
      "smelting": { "synonyms": ["pyrometallurgy", "matte smelting", "reduction smelting", "flash smelting"] },
      "sintering": { "synonyms": ["agglomeration", "firing", "nodulizing"] },
      "solvent extraction": { "synonyms": ["liquid extraction", "sx", "selective extraction"] },
      "sorption": { "synonyms": ["adsorption", "chemisorption", "ion exchange"] },
      "thickening": { "synonyms": ["paste thickening", "gravity thickening", "sedimentation"] },
      "washing": { "synonyms": ["scrubbing", "rinsing", "counter-current washing"] }
    }
  },
  "Equipment": {
    "ru": {
      "автоклав": { "synonyms": ["реактор высокого давления", "промышленный автоклав", "автоклав для выщелачивания", "титановый автоклав", "аппарат давления"] },
      "печь": { "synonyms": ["руднотермическая печь", "ртп", "электропечь", "печь Ванюкова", "печь кипящего слоя", "шахтная печь", "конвертер", "печь для плавки", "печь для обжига"] },
      "реактор": { "synonyms": ["реактор выщелачивания", "химический реактор", "реактор с мешалкой", "колонный реактор", "реактор для цементации"] },
      "конвертер": { "synonyms": ["конвертер для плавки", "бессемеровский конвертер", "кислородный конвертер", "конвертер для штейна"] },
      "электролизер": { "synonyms": ["ванна электролиза", "электролизная ванна", "электролизная ячейка", "электролизер для рафинирования"] },
      "фильтр": { "synonyms": ["вакуум-фильтр", "пресс-фильтр", "фильтр-пресс", "дисковый фильтр", "ленточный фильтр", "фильтрующее оборудование"] },
      "флотационная машина": { "synonyms": ["флотомашина", "пневмомеханическая флотационная машина", "колонная флотационная машина", "флотационная камера"] },
      "мельница": { "synonyms": ["шаровая мельница", "стержневая мельница", "мельница мокрого измельчения", "дробилка", "измельчитель"] },
      "насос": { "synonyms": ["центробежный насос", "мембранный насос", "пульповый насос", "питательный насос", "шламовый насос"] },
      "трубопровод": { "synonyms": ["трубопровод для пульпы", "напорный трубопровод", "транспортный трубопровод", "газоход", "сталь", "пульповод"] },
      "бункер": { "synonyms": ["приемный бункер", "концентратный бункер", "шихтовый бункер", "дозатор"] },
      "классификатор": { "synonyms": ["гидроциклон", "спиральный классификатор", "центробежный классификатор", "грохот", "виброгрохот", "барабанный грохот"] },
      "сепаратор": { "synonyms": ["магнитный сепаратор", "электростатический сепаратор", "центробежный сепаратор", "сепаратор для обогащения"] },
      "сушилка": { "synonyms": ["барабанная сушилка", "распылительная сушилка", "вакуумная сушилка", "сушильная установка"] },
      "кристаллизатор": { "synonyms": ["вакуумный кристаллизатор", "охлаждающий кристаллизатор", "аппарат кристаллизации"] },
      "газоочистка": { "synonyms": ["скруббер", "аппарат мокрой очистки", "электрофильтр", "рукавный фильтр", "газопромыватель"] },
      "компрессор": { "synonyms": ["воздушный компрессор", "поршневой компрессор", "винтовой компрессор"] },
      "дозатор": { "synonyms": ["реагентный дозатор", "дозирующее устройство", "питатель", "дозировочный насос"] },
      "гранулятор": { "synonyms": ["барабанный гранулятор", "дисковый гранулятор", "агломератор"] },
      "агитатор": { "synonyms": ["мешалка", "пропеллерная мешалка", "турбинная мешалка", "установка для перемешивания"] },
      "емкость": { "synonyms": ["хранилище", "резервуар", "бак", "сборник раствора", "пруд-накопитель", "отстойник"] },
      "конвейер": { "synonyms": ["ленточный конвейер", "скребковый конвейер", "транспортер", "питатель"] },
      "теплообменник": { "synonyms": ["подогреватель", "охладитель", "змеевиковый теплообменник", "рекуператор"] },
      "отстойник": { "synonyms": ["сгуститель", "радиальный сгуститель", "отстойник для пульпы"] },
      "сито": { "synonyms": ["грохот", "вибрационное сито", "барабанное сито"] },
      "бак": { "synonyms": ["реакционный бак", "растворный бак", "промежуточная емкость", "накопитель"] },
      "сгуститель": { "synonyms": ["радиальный сгуститель", "пастовый сгуститель", "аппарат для сгущения", "гравитационный сгуститель"] },
      "миксер": { "synonyms": ["смеситель", "пневмомеханический смеситель", "эмульсионный смеситель"] },
      "пульпопровод": { "synonyms": ["пульповый трубопровод", "шламопровод", "трубопровод для шлама"] },
      "дымосос": { "synonyms": ["вентилятор", "экстаустер", "дымовая труба", "газодувка"] },
      "зумпф": { "synonyms": ["приемная емкость", "сборник шлама", "насосный зумпф"] },
      "печь Ванюкова": { "synonyms": ["пв", "печь взвешенной плавки", "ваньковская печь"] },
      "реактор автоклавный": { "synonyms": ["реактор автоклавного выщелачивания", "автоклавная установка"] },
      "центрифуга": { "synonyms": ["фильтрующая центрифуга", "осадительная центрифуга", "декантер"] },
      "электродвигатель": { "synonyms": ["электромотор", "привод", "двигатель", "генератор"] },
      "аппарат": { "synonyms": ["химический аппарат", "технологическая установка", "оборудование", "машина"] },
      "установка": { "synonyms": ["насосная станция", "компрессорная станция", "установка обезвоживания", "технологическая линия"] },
      "скруббер": { "synonyms": ["газопромыватель", "мокрый пылеуловитель", "абсорбер"] },
      "электрофильтр": { "synonyms": ["электростатический фильтр", "осадительный электрод"] },
      "смеситель": { "synonyms": ["эмульсионный смеситель", "диспергатор", "гомогенизатор"] },
      "абсорбер": { "synonyms": ["скруббер", "газопромыватель", "колонна абсорбции", "насадочная колонна"] },
      "автоклав": { "synonyms": ["реактор высокого давления", "промышленный автоклав", "автоклав для выщелачивания", "титановый автоклав", "аппарат давления"] },
      "агитатор": { "synonyms": ["мешалка", "пропеллерная мешалка", "турбинная мешалка", "установка для перемешивания"] },
      "аппарат": { "synonyms": ["химический аппарат", "технологическая установка", "оборудование", "машина"] },
      "бак": { "synonyms": ["реакционный бак", "растворный бак", "промежуточная емкость", "накопитель"] },
      "бункер": { "synonyms": ["приемный бункер", "концентратный бункер", "шихтовый бункер", "дозатор"] },
      "вакуум-фильтр": { "synonyms": ["фильтр", "дисковый вакуум-фильтр", "барабанный вакуум-фильтр", "вакуумная установка"] },
      "виброгрохот": { "synonyms": ["грохот", "вибрационное сито", "инерционный грохот", "барабанный грохот"] },
      "газоход": { "synonyms": ["дымоход", "трубопровод для газов", "воздуховод", "боров"] },
      "гранулятор": { "synonyms": ["барабанный гранулятор", "дисковый гранулятор", "агломератор"] },
      "декантатор": { "synonyms": ["отстойник", "сгуститель", "осветлитель", "радиальный отстойник"] },
      "дисковый фильтр": { "synonyms": ["вакуум-дисковый фильтр", "фильтр-диск", "дисковая вакуум-установка"] },
      "дозатор": { "synonyms": ["реагентный дозатор", "дозирующее устройство", "питатель", "дозировочный насос"] },
      "дробилка": { "synonyms": ["щековая дробилка", "конусная дробилка", "валковая дробилка", "роторная дробилка"] },
      "дымосос": { "synonyms": ["вентилятор", "экстаустер", "дымовая труба", "газодувка"] },
      "ёмкость": { "synonyms": ["хранилище", "резервуар", "бак", "сборник раствора", "пруд-накопитель", "отстойник"] },
      "зумпф": { "synonyms": ["приемная емкость", "сборник шлама", "насосный зумпф"] },
      "ионитная колонна": { "synonyms": ["колонна ионного обмена", "сорбционная колонна", "ионообменный фильтр"] },
      "классификатор": { "synonyms": ["гидроциклон", "спиральный классификатор", "центробежный классификатор", "грохот"] },
      "компрессор": { "synonyms": ["воздушный компрессор", "поршневой компрессор", "винтовой компрессор"] },
      "конвейер": { "synonyms": ["ленточный конвейер", "скребковый конвейер", "транспортер", "питатель"] },
      "конвертер": { "synonyms": ["конвертер для плавки", "бессемеровский конвертер", "кислородный конвертер", "конвертер для штейна"] },
      "кристаллизатор": { "synonyms": ["вакуумный кристаллизатор", "охлаждающий кристаллизатор", "аппарат кристаллизации"] },
      "мельница": { "synonyms": ["шаровая мельница", "стержневая мельница", "мельница мокрого измельчения"] },
      "миксер": { "synonyms": ["смеситель", "пневмомеханический смеситель", "эмульсионный смеситель"] },
      "насос": { "synonyms": ["центробежный насос", "мембранный насос", "пульповый насос", "питательный насос", "шламовый насос"] },
      "отстойник": { "synonyms": ["сгуститель", "радиальный сгуститель", "отстойник для пульпы"] },
      "печь": { "synonyms": ["руднотермическая печь", "ртп", "электропечь", "печь Ванюкова", "печь кипящего слоя", "шахтная печь", "конвертер"] },
      "печь Ванюкова": { "synonyms": ["пв", "печь взвешенной плавки", "ваньковская печь"] },
      "пресс-фильтр": { "synonyms": ["фильтр-пресс", "камерный пресс-фильтр", "мембранный пресс-фильтр"] },
      "пульпопровод": { "synonyms": ["пульповый трубопровод", "шламопровод", "трубопровод для шлама"] },
      "реактор": { "synonyms": ["реактор выщелачивания", "химический реактор", "реактор с мешалкой", "колонный реактор", "реактор для цементации"] },
      "сгуститель": { "synonyms": ["радиальный сгуститель", "пастовый сгуститель", "аппарат для сгущения", "гравитационный сгуститель"] },
      "сепаратор": { "synonyms": ["магнитный сепаратор", "электростатический сепаратор", "центробежный сепаратор", "сепаратор для обогащения"] },
      "сито": { "synonyms": ["грохот", "вибрационное сито", "барабанное сито"] },
      "скруббер": { "synonyms": ["газопромыватель", "мокрый пылеуловитель", "абсорбер"] },
      "смеситель": { "synonyms": ["эмульсионный смеситель", "диспергатор", "гомогенизатор"] },
      "сушилка": { "synonyms": ["барабанная сушилка", "распылительная сушилка", "вакуумная сушилка", "сушильная установка"] },
      "теплообменник": { "synonyms": ["подогреватель", "охладитель", "змеевиковый теплообменник", "рекуператор"] },
      "фильтр": { "synonyms": ["вакуум-фильтр", "пресс-фильтр", "фильтр-пресс", "дисковый фильтр", "ленточный фильтр", "фильтрующее оборудование"] },
      "флотационная машина": { "synonyms": ["флотомашина", "пневмомеханическая флотационная машина", "колонная флотационная машина", "флотационная камера"] },
      "центрифуга": { "synonyms": ["фильтрующая центрифуга", "осадительная центрифуга", "декантер"] },
      "электродвигатель": { "synonyms": ["электромотор", "привод", "двигатель", "генератор"] },
      "электролизер": { "synonyms": ["ванна электролиза", "электролизная ванна", "электролизная ячейка", "электролизер для рафинирования"] },
      "электрофильтр": { "synonyms": ["электростатический фильтр", "осадительный электрод"] }
    },
    "en": {
      "autoclave": { "synonyms": ["pressure reactor", "industrial autoclave", "leaching autoclave", "titanium autoclave", "pressure vessel"] },
      "furnace": { "synonyms": ["electro-furnace", "vanyukov furnace", "fluidized bed furnace", "shaft furnace", "converter", "smelting furnace", "roasting furnace"] },
      "reactor": { "synonyms": ["leaching reactor", "chemical reactor", "stirred tank reactor", "column reactor", "precipitation reactor"] },
      "converter": { "synonyms": ["converter furnace", "bessemer converter", "oxygen converter"] },
      "electrolyzer": { "synonyms": ["electrolysis cell", "electrolytic cell", "refining tank"] },
      "filter": { "synonyms": ["vacuum filter", "press filter", "filter press", "disc filter", "belt filter", "filtration equipment"] },
      "flotation machine": { "synonyms": ["flotation cell", "pneumatic-mechanical flotation machine", "column flotation cell", "flotation tank"] },
      "mill": { "synonyms": ["ball mill", "rod mill", "wet mill", "crusher", "grinder"] },
      "pump": { "synonyms": ["centrifugal pump", "diaphragm pump", "slurry pump", "feed pump"] },
      "pipeline": { "synonyms": ["slurry pipeline", "pressure pipeline", "transport pipeline", "flue", "steel pipe"] },
      "hopper": { "synonyms": ["receive hopper", "concentrate bin", "batch bin", "feeder"] },
      "classifier": { "synonyms": ["hydrocyclone", "spiral classifier", "centrifugal classifier", "screen", "vibrating screen", "trommel"] },
      "separator": { "synonyms": ["magnetic separator", "electrostatic separator", "centrifugal separator"] },
      "dryer": { "synonyms": ["rotary dryer", "spray dryer", "vacuum dryer", "drying plant"] },
      "crystallizer": { "synonyms": ["vacuum crystallizer", "cooling crystallizer", "crystallization apparatus"] },
      "gas cleaning": { "synonyms": ["scrubber", "wet scrubber", "electrostatic precipitator", "bag filter", "gas washer"] },
      "compressor": { "synonyms": ["air compressor", "piston compressor", "screw compressor"] },
      "feeder": { "synonyms": ["reagent feeder", "dosing device", "metering pump"] },
      "granulator": { "synonyms": ["rotary granulator", "disc granulator", "agglomerator"] },
      "agitator": { "synonyms": ["mixer", "propeller agitator", "turbine agitator", "stirrer"] },
      "tank": { "synonyms": ["storage tank", "reservoir", "solution tank", "settling basin"] },
      "conveyor": { "synonyms": ["belt conveyor", "scraper conveyor", "feeder", "transporter"] },
      "heat exchanger": { "synonyms": ["heater", "cooler", "coil heat exchanger", "recuperator"] },
      "thickener": { "synonyms": ["settler", "radial thickener", "clarifier"] },
      "screen": { "synonyms": ["vibrating screen", "trommel screen", "sieve"] },
      "vessel": { "synonyms": ["reaction vessel", "storage tank", "intermediate vessel"] },
      "thickener": { "synonyms": ["paste thickener", "gravity thickener", "settling apparatus"] },
      "mixer": { "synonyms": ["emulsion mixer", "disperser", "homogenizer"] },
      "slurry pipeline": { "synonyms": ["sludge pipeline", "tailings pipeline"] },
      "fan": { "synonyms": ["exhauster", "blower", "stack", "gas fan"] },
      "sump": { "synonyms": ["receiving tank", "sludge pump sump"] },
      "vanyukov furnace": { "synonyms": ["flash smelting furnace", "vanyukov process furnace"] },
      "autoclave reactor": { "synonyms": ["pressure oxidation reactor", "autoclave plant"] },
      "centrifuge": { "synonyms": ["filtering centrifuge", "decanter", "sedimentation centrifuge"] },
      "motor": { "synonyms": ["electric motor", "drive", "engine", "generator"] },
      "apparatus": { "synonyms": ["chemical apparatus", "technological unit", "equipment", "machine"] },
      "plant": { "synonyms": ["pumping station", "compressor station", "dewatering plant", "processing line"] },
      "scrubber": { "synonyms": ["gas washer", "wet dust collector", "absorber"] },
      "electrostatic precipitator": { "synonyms": ["esp", "dust precipitator"] },
      "mixer": { "synonyms": ["emulsion mixer", "disperser", "homogenizer"] },
      "absorber": { "synonyms": ["scrubber", "gas washer", "absorption column", "packed column"] },
      "agitator": { "synonyms": ["mixer", "stirrer", "impeller", "propeller agitator"] },
      "autoclave": { "synonyms": ["pressure vessel", "high-pressure reactor", "leaching autoclave", "titanium autoclave"] },
      "bag filter": { "synonyms": ["dust collector", "fabric filter", "baghouse"] },
      "bin": { "synonyms": ["hopper", "storage bin", "concentrate bin", "feed bin"] },
      "centrifuge": { "synonyms": ["decanter", "filtering centrifuge", "sedimentation centrifuge"] },
      "classifier": { "synonyms": ["hydrocyclone", "spiral classifier", "centrifugal classifier", "screen"] },
      "compressor": { "synonyms": ["air compressor", "piston compressor", "screw compressor"] },
      "conveyor": { "synonyms": ["belt conveyor", "scraper conveyor", "feeder", "transporter"] },
      "crusher": { "synonyms": ["jaw crusher", "cone crusher", "roll crusher", "impact crusher"] },
      "crystallizer": { "synonyms": ["vacuum crystallizer", "cooling crystallizer", "evaporative crystallizer"] },
      "decanter": { "synonyms": ["settler", "thickener", "clarifier", "radial decanter"] },
      "doser": { "synonyms": ["reagent feeder", "metering pump", "dispenser", "proportioner"] },
      "dryer": { "synonyms": ["rotary dryer", "spray dryer", "vacuum dryer", "drying plant"] },
      "electrolyzer": { "synonyms": ["electrolysis cell", "electrolytic cell", "refining tank"] },
      "electrostatic precipitator": { "synonyms": ["esp", "dust precipitator", "electrofilter"] },
      "fan": { "synonyms": ["exhauster", "blower", "stack", "gas fan"] },
      "filter": { "synonyms": ["vacuum filter", "press filter", "filter press", "disc filter", "belt filter"] },
      "filter press": { "synonyms": ["chamber filter press", "membrane filter press", "plate filter"] },
      "flotation machine": { "synonyms": ["flotation cell", "pneumatic-mechanical flotation machine", "column flotation cell"] },
      "furnace": { "synonyms": ["electro-furnace", "vanyukov furnace", "fluidized bed furnace", "shaft furnace"] },
      "gas duct": { "synonyms": ["flue", "gas pipeline", "air duct", "breeching"] },
      "granulator": { "synonyms": ["rotary granulator", "disc granulator", "agglomerator"] },
      "heat exchanger": { "synonyms": ["heater", "cooler", "coil heat exchanger", "recuperator"] },
      "hopper": { "synonyms": ["receive hopper", "concentrate bin", "batch bin"] },
      "ion exchange column": { "synonyms": ["sorption column", "ion exchange filter", "resin column"] },
      "mill": { "synonyms": ["ball mill", "rod mill", "wet mill", "crusher"] },
      "mixer": { "synonyms": ["emulsion mixer", "disperser", "homogenizer"] },
      "motor": { "synonyms": ["electric motor", "drive", "engine", "generator"] },
      "pipeline": { "synonyms": ["slurry pipeline", "pressure pipeline", "transport pipeline"] },
      "pump": { "synonyms": ["centrifugal pump", "diaphragm pump", "slurry pump", "feed pump"] },
      "reactor": { "synonyms": ["leaching reactor", "chemical reactor", "stirred tank reactor", "column reactor"] },
      "screen": { "synonyms": ["vibrating screen", "trommel", "sieve", "shaker screen"] },
      "scrubber": { "synonyms": ["gas washer", "wet dust collector", "absorber"] },
      "separator": { "synonyms": ["magnetic separator", "electrostatic separator", "centrifugal separator"] },
      "sump": { "synonyms": ["receiving tank", "sludge pump sump"] },
      "tank": { "synonyms": ["storage tank", "reservoir", "solution tank", "settling basin"] },
      "thickener": { "synonyms": ["paste thickener", "gravity thickener", "settling apparatus"] },
      "vanyukov furnace": { "synonyms": ["flash smelting furnace", "vanyukov process furnace"] },
      "vessel": { "synonyms": ["reaction vessel", "storage tank", "intermediate vessel"] },
      "wet scrubber": { "synonyms": ["gas washer", "spray tower", "venturi scrubber"] }
    }
  }
}